version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://root:password@mongodb:27017/mentor_stats
    depends_on:
      - database
      - mongodb
    networks:
      - my-network

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - my-network

  database:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_USER: postgres
      POSTGRES_DB: speed_drive
    networks:
      - my-network

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mentor_stats
    volumes:
      - mongodb-data:/data/db
      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    env_file:
      - .env
    command: [--auth]
    networks:
      - my-network

volumes:
  mongodb-data:

networks:
  my-network:
    driver: bridge
